[workspace]
members = ["xtask/", "crates/*"]
resolver = "2"

[workspace.package]
rust-version = "1.81"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Victor Pogor"]
repository = "https://github.com/victor-pogor/rust-off"

[profile.dev]
debug = "full" # This is the default.
# opt-level = 0 # 0 is faster, 3 is slower but more optimized.
# overflow-checks = false # Disable integer overflow checks.

[profile.dev.package]
# These speed up local tests.
serde.opt-level = 3
rowan.opt-level = 3

[profile.release]
incremental = true
# Set this to 1 or 2 to get more useful backtraces in debugger.
debug = 0
opt-level = 3

# non-local crates

[workspace.lints.clippy]

[workspace.dependencies]
# local crates
stdx = { path = "./crates/stdx", version = "0.0.0" }
pdfc-lexer = { path = "./crates/lexer", version = "0.0.0" }
edition = { path = "./crates/edition", version = "0.0.0" }
pdfc-parser = { path = "./crates/parser", version = "0.0.0" }
limit = { path = "./crates/limit", version = "0.0.0" }

# non-local crates
anyhow = "1.0.97"
xshell = "0.2.7"
itertools = "0.14.0"
either = "1.14.0"
tracing = "0.1.41"
