[package]
name = "hir-def"
version = "0.0.0"
description = "RPC Api for the `proc-macro-srv` crate of rust-analyzer."

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
# Non-local deps
rustc_apfloat = "0.2.2"
la-arena.workspace = true
salsa.workspace = true
smallvec.workspace = true


# Local deps
intern.workspace = true
pdfc-syntax.workspace = true
pdfc-lexer.workspace = true
span.workspace = true
stdx.workspace = true
base-db.workspace = true

[dev-dependencies]
# Non-local deps

# Local deps

[lints]
workspace = true
