version: '3'
services:
  pdfc-lexer:
    # use the docker image from the Dockerfile
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.rust
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    links:
      - pdfc-web
  pdfc-web:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity