version: '3'
services:
  rusted-pdf:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.rust
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    links:
      - rusted-pdf-web
  rusted-pdf-web:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ..:/workspace:cached
    command: sleep infinity