[package]
name = "pdfc-lexer"
version = "0.1.0"
description = "PDF content lexer."

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]

[lints]
workspace = true

[dev-dependencies]
csv = "1.3.1"
serde = { version = "1.0.217", features = ["derive"] }
