[package]
name = "base-db"
version = "0.0.0"
description = "Basic database traits for rust-analyzer."

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
# Add any dependencies required for your project here
vfs.workspace = true
salsa.workspace = true
triomphe.workspace = true
tracing.workspace = true
la-arena.workspace = true
query-group.workspace = true
span.workspace = true
rustc-hash.workspace = true
pdfc-syntax.workspace = true

[dev-dependencies]
# Add any development dependencies here

[lints]
workspace = true
