name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - lexer
          - parser
    defaults:
      run:
        working-directory: ./crates/${{ matrix.crate }}
    name: Build and Test the ${{ matrix.crate }} crate
    steps:
    - uses: actions/checkout@v4
    - name: Build ${{ matrix.crate }}
      run: cargo build --verbose
    - name: Run tests ${{ matrix.crate }}
      run: cargo test --verbose